name: flutter_datawedge
description: A Flutter package to communicate with Zebra DataWedge scanners using the DataWedge Intent API
version: 3.0.0
homepage: https://github.com/circus-kitchens/flutter_datawedge
repository: https://github.com/circus-kitchens/flutter_datawedge

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.1"

dependencies:
  async: ^2.11.0
  collection: 1.18.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  freezed_result: ^1.0.3+1
  json_annotation: ^4.9.0
  mason_logger: ^0.3.1
  stream_transform: ^2.1.0
  strict_json: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  pigeon: ^22.6.2
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.circuskitchens.flutter_datawedge
        pluginClass: FlutterDatawedgePlugin
